# run me with: docker-compose -f docker-compose.local.yml up

version: '3.8'

services:

  postgres:
    build:
      context: .
      dockerfile: ./Database/Dockerfile
    restart: always
    ports:
      - "5432:5432"

  broker:
    container_name: "broker"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=muscleUp
      - RABBITMQ_DEFAULT_PASS=Pa55w0rd
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  auth:
    build: 
      context: .
      dockerfile: ./Auth/Auth.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JwtSecret
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
    depends_on:
      - postgres

  carnets:
    build:
      context: .
      dockerfile: ./Carnets/Carnets.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JwtSecret
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
      - Api:FitnessClubHost=http://fitnessclubs/
      - Broker:Host:HostName=broker
    depends_on:
      - postgres
      - broker

  apigateway:
    build:
      context: .
      dockerfile: ./ApiGateway/ApiGateway.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+;https://+
    ports:
      - "8079:80"
      - "8082:443"
    depends_on:
      - auth
      - carnets
