# run me with: docker-compose up

version: '3.8'

services:

  postgres:
    image: ghcr.io/muscle-up-app/database
    restart: always

  broker:
    container_name: "broker"
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: 'muscleUp'
      RABBITMQ_DEFAULT_PASS: 'Pa55w0rd'
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  auth:
    image: ghcr.io/muscle-up-app/auth
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__DefaultConnection: 'Server=postgres;Port=5432;Database=Auth;User Id=postgres;Password=Pa55w0rd;'
    depends_on:
      - postgres

  carnets:
    image: ghcr.io/muscle-up-app/carnets
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__DefaultConnection: 'Server=postgres;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;'
      Api__FitnessClubHost: 'http://fitnessclubs/'
      Api__AuthHost: 'http://auth/'
      Broker__Host__HostName: 'broker'
    depends_on:
      - postgres
      - broker

  fitnessclubs:
    image: ghcr.io/muscle-up-app/fitnessclubs
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__DefaultConnection: 'Server=postgres;Port=5432;Database=FitnessClubs;User Id=postgres;Password=Pa55w0rd;'
      Api__AuthHost: 'http://auth/'
      Broker__Host__HostName: 'broker'
    depends_on:
      - postgres
      - broker

  content:
    image: ghcr.io/muscle-up-app/content
    restart: always
    environment:
      DATASOURCE_PORT: 'postgres:5432'
      DATASOURCE_USERNAME: 'postgres'
      DATASOURCE_PASSWORD: 'Pa55w0rd'
      APPLICATION_CONTEXT: 'prod'
    depends_on:
      - postgres

  groups:
    image: ghcr.io/muscle-up-app/groups
    restart: always
    environment:
      DATASOURCE_PORT: 'postgres:5432'
      DATASOURCE_USERNAME: 'postgres'
      DATASOURCE_PASSWORD: 'Pa55w0rd'
      APPLICATION_CONTEXT: 'prod'
      FUTURE_GROUP_CREATIONS: 2
    depends_on:
      - postgres

  notifications:
    image: ghcr.io/muscle-up-app/notifications
    restart: always
    environment:
      DATASOURCE_PORT: 'postgres:5432'
      DATASOURCE_USERNAME: 'postgres'
      DATASOURCE_PASSWORD: 'Pa55w0rd'
      APPLICATION_CONTEXT: 'prod'
    depends_on:
      - postgres

  apigateway:
    image: ghcr.io/muscle-up-app/apigateway
    restart: always
    environment:
      ASPNETCORE_URLS: 'http://+;https://+'
    ports:
      - "8080:80"
      - "8082:443"
    depends_on:
      - auth
      - carnets
      - fitnessclubs
      - content
      - groups
      - notifications
