# run me with: docker-compose -f docker-compose.dotnet.yml up --build

version: '3.8'

services:

  postgres:
    build:
      context: .
      dockerfile: ./Database/Dockerfile
    restart: always
    ports:
      - "5432:5432"

  auth:
    build: 
      context: .
      dockerfile: ./Auth/Auth.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JwtSecret
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
    depends_on:
      - postgres

  carnets:
    build: 
      context: .
      dockerfile: ./Carnets/Carnets.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JwtSecret
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
      - Api:FitnessClubHost=http://fitnessclubs/
    depends_on:
      - postgres

  fitnessclubs:
    build: 
      context: .
      dockerfile: ./FitnessClubs/FitnessClubs.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JwtSecret
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=FitnessClubs;User Id=postgres;Password=Pa55w0rd;
      - Api:Auth=http://auth/
    depends_on:
      - postgres

  apigateway:
    build: 
      context: .
      dockerfile: ./ApiGateway/ApiGateway.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+;https://+
    ports:
      - "8080:80"
      - "8082:443"
    depends_on:
      - auth
      - carnets
      - fitnessclubs
