# run me with: docker-compose -f docker-compose.build.yml up --build

version: '3.8'

services:
  dbauth:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd
    ports:
      - "5432:5432"

  dbgroups:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd

  dbcarnets:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd

  dbfitnessclubs:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd

  dbcontent:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd

  auth:
    build: 
      context: .
      dockerfile: ./Auth/Auth.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=dbauth;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
    depends_on:
      - dbauth

  carnets:
    build: 
      context: .
      dockerfile: ./Carnets/Carnets.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=dbcarnets;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
    depends_on:
      - dbcarnets

  fitnessclubs:
    build: 
      context: .
      dockerfile: ./FitnessClubs/FitnessClubs.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=dbfitnessclubs;Port=5432;Database=FitnessClubs;User Id=postgres;Password=Pa55w0rd;
    depends_on:
      - dbfitnessclubs

  apigateway:
    build: 
      context: .
      dockerfile: ./ApiGateway/ApiGateway.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+;https://+
    ports:
      - "8080:80"
      - "8082:443"
    depends_on:
      - auth
      - carnets
      - fitnessclubs