# run me with: docker-compose -f docker-compose.local.yml up

version: '3.8'

services:

  postgres:
    build:
      context: .
      dockerfile: ./Database/Dockerfile
    restart: always
    ports:
      - "5432:5432"

  auth:
    build: 
      context: .
      dockerfile: ./Auth/Auth.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JwtSecret
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
    depends_on:
      - postgres
