# run me with: docker-compose -f docker-compose.local.yml up

version: '3.8'

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=Pa55w0rd
    ports:
      - "5432:5432"
    volumes:
      - ./Database/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql

  auth:
    build: 
      context: .
      dockerfile: ./Auth/Auth.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT
      - JwtSecret
      - ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=Carnets;User Id=postgres;Password=Pa55w0rd;
    depends_on:
      - postgres
